# Generated by Django 4.2.11 on 2025-05-27 16:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('subtitle', models.TextField()),
                ('body', models.TextField()),
                ('slug', models.SlugField(blank=True)),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='posts/featured/')),
                ('featured_post', models.BooleanField(default=False)),
                ('tags', models.ManyToManyField(related_name='post_tag', to='blog.tag')),
            ],
            options={
                'ordering': ['-date_posted'],
            },
        ),
    ]
